export const FETCH_SURVEY_CONFIG_REQUEST = "FETCH_SURVEY_CONFIG_REQUEST";
export const FETCH_SURVEY_CONFIG_SUCCESS = "FETCH_SURVEY_CONFIG_SUCCESS";
export const FETCH_SURVEY_CONFIG_FAILURE = "FETCH_SURVEY_CONFIG_FAIL";

export const UPDATE_SURVEY_DATA = "UPDATE_SURVEY_DATA";
export const RESET_SURVEY_DATA = "RESET_SURVEY_DATA";

export const SUBMIT_SURVEY_REQUEST = "SUBMIT_SURVEY_REQUEST";
export const SUBMIT_SURVEY_SUCCESS = "SUBMIT_SURVEY_SUCCESS";
export const SUBMIT_SURVEY_FAILURE = "SUBMIT_SURVEY_FAILURE";

export const RESET_SUBMIT_STATUS = "RESET_SUBMIT_STATUS";
