export const FETCH_SURVEY_CONFIG_REQUEST = "FETCH_SURVEY_CONFIG_REQUEST";
export const FETCH_SURVEY_CONFIG_SUCCESS = "FETCH_SURVEY_CONFIG_SUCCESS";
export const FETCH_SURVEY_CONFIG_FAILURE = "FETCH_SURVEY_CONFIG_FAIL";
